// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ISxLxr09JeYwUbIvwTPd9oTuBbYItuA',
    appId: '1:710812099389:web:e0ea8a49c17bda0b451b54',
    messagingSenderId: '710812099389',
    projectId: 'plant-50eb9',
    authDomain: 'plant-50eb9.firebaseapp.com',
    storageBucket: 'plant-50eb9.appspot.com',
    measurementId: 'G-C7260FLFZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiQ66h2b1pZ5oYiDreAzq35yyWMB_Uw70',
    appId: '1:710812099389:android:53538d248998ddcf451b54',
    messagingSenderId: '710812099389',
    projectId: 'plant-50eb9',
    storageBucket: 'plant-50eb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy97XEMPONgy12Uu6Mv5WjhKUlVAgwnUc',
    appId: '1:710812099389:ios:a48497be5aa9f80a451b54',
    messagingSenderId: '710812099389',
    projectId: 'plant-50eb9',
    storageBucket: 'plant-50eb9.appspot.com',
    iosClientId: '710812099389-o21gv4h1sc22k5l2bb7m8h6drsps0et6.apps.googleusercontent.com',
    iosBundleId: 'com.eplant.ePlant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy97XEMPONgy12Uu6Mv5WjhKUlVAgwnUc',
    appId: '1:710812099389:ios:a48497be5aa9f80a451b54',
    messagingSenderId: '710812099389',
    projectId: 'plant-50eb9',
    storageBucket: 'plant-50eb9.appspot.com',
    iosClientId: '710812099389-o21gv4h1sc22k5l2bb7m8h6drsps0et6.apps.googleusercontent.com',
    iosBundleId: 'com.eplant.ePlant',
  );
}
